FROM nginx

COPY nginx.config /etc/nginx/conf.d/default.conf
COPY public/index.html /usr/share/nginx/html
RUN mkdir -p /usr/share/nginx/html/assets
COPY public/assets/*.js /usr/share/nginx/html/assets
COPY public/assets/*.css /usr/share/nginx/html/assets
