apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  # namespace: backend
  # annotations:
  #   kubernetes.io/ingress.class: "nginx" 
  #   cert-manager.io/issuer: letsencrypt-staging
spec:
  rules:
  - host: api.pathfinderspelldb.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pfsdb-server-service
            port:
              number: 80
  - host: pathfinderspelldb.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pfsdb-client-service
            port:
              number: 80
  ingressClassName: nginx